/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-27 10:01:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.semi.qna.model.vo.*;
import java.util.*;

public final class admin_005fquestions_005f4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/common/admin_header.jsp", Long.valueOf(1582645754411L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.kh.semi.qna.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 
	ArrayList<Qna> list = (ArrayList<Qna>)request.getAttribute("list"); 
	QPageInfo qpi = (QPageInfo)request.getAttribute("qpi");
	int listCount = qpi.getListCount();
	int currentPage = qpi.getCurrentPage();
	int maxPage = qpi.getMaxPage();
	int startPage = qpi.getStartPage();
	int endPage = qpi.getEndPage();	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>문의사항</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/siktam/resources/css/admin_4.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/siktam/resources/css/notice_5.css\">\r\n");
      out.write("\t\r\n");
      out.write("  <style>\r\n");
      out.write(".wrap {\r\n");
      out.write("\tpadding-top: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#searchBtn{\r\n");
      out.write("\tbackground: rgb(110, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table thead tr{\r\n");
      out.write("    border-bottom: 2px solid rgb(110, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination{\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"height:1080px\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".container-fluid {\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  padding-left: 15%;\r\n");
      out.write("  padding-right: 15%;\r\n");
      out.write("  height: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-inverse .navbar-nav>.active>a, .navbar-inverse .navbar-nav>.active>a:focus, .navbar-inverse .navbar-nav>.active>a:hover {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color: #080808;\r\n");
      out.write("    height: 60px;\r\n");
      out.write("    margin: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-inverse .navbar-nav>li>a {\r\n");
      out.write("    color: white;\r\n");
      out.write("    height: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-inverse .navbar-nav>.active>a{\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav{\r\n");
      out.write("    margin-right: 0;\r\n");
      out.write("    /* border: 1px solid black; */\r\n");
      out.write("    text-align: right;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("    \r\n");
      out.write("<header>\r\n");
      out.write("  <nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <div class=\"navbar-header\">\r\n");
      out.write("        <div id=\"logodiv\"><a href=\"/siktam/listMain.ma\"><img id=\"logo\" src=\"/siktam/resources/images/KakaoTalk_20200101_193858750.png\" alt=\"\" style=\"width:50px; height:50px\"></a></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("        <li class=\"\"><a href=\"/siktam/views/admin_main_4.jsp\">관리자메인</a></li>\r\n");
      out.write("        <li class=\"dropdown active\">\r\n");
      out.write("          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">회원관리 <span class=\"caret\"></span></a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a href=\"/siktam/selectList.me\">회원리스트</a></li>\r\n");
      out.write("            <li><a href=\"/siktam/sAdminList.sh\">업체리스트</a></li>\r\n");
      out.write("            <li><a href=\"/siktam/bList.bl\">블랙리스트</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">사이트관리 <span class=\"caret\"></span></a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a href=\"/siktam/nselectList.no\">공지사항</a></li>\r\n");
      out.write("            <li><a href=\"/siktam/eSelectList.ev\">이벤트배너</a></li>\r\n");
      out.write("            <li><a href=\"/siktam/qAdminList.qna\">문의사항</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"wrap\" align=\"center\">\r\n");
      out.write("            <div class=\"noticeTitle\">\r\n");
      out.write("                <h1>답변을 기다리는 문의사항</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"tableDiv\">\r\n");
      out.write("                    <table id=\"listArea\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                              <th>글번호</th>\r\n");
      out.write("                              <th>아이디</th>\r\n");
      out.write("                              <th>제목</th>\r\n");
      out.write("                              <th>내용</th>\r\n");
      out.write("                              <th>작성일</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            ");
 for(Qna qna : list){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print( qna.getqNo() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print( qna.getUserId() );
      out.write("</td>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print( qna.getqTitle() );
      out.write("</td>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print( qna.getqContext() );
      out.write("</td>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print( qna.getqDate() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <br>\r\n");
      out.write("            \r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"pagingArea\" align=\"center\">\r\n");
      out.write("\t\t\t\t<div class=\"page\">\r\n");
      out.write("\t\t\t      <ul class=\"pagination\">\r\n");
      out.write("\t\t\t      \t<li><a onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/qAdminList.qna?currentPage=1'\"><<</a></li>\r\n");
      out.write("\t\t\t        <li>\r\n");
      out.write("\t\t\t        \t");
  if(currentPage <= 1){  
      out.write("\r\n");
      out.write("\t\t\t        \t<a><</a>\r\n");
      out.write("\t\t\t\t\t\t");
  }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/qAdminList.qna?currentPage=");
      out.print(currentPage - 1 );
      out.write("'\"><</a>\r\n");
      out.write("\t\t\t\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t        </li>\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t        ");
 for(int p = startPage; p <= endPage; p++){
							if(p == currentPage){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a style=\"background: rgb(110, 0, 0); color: white\">");
      out.print( p );
      out.write("</a><li>\r\n");
      out.write("\t\t\t\t\t");
      }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/qAdminList.qna?currentPage=");
      out.print( p );
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a><li>\r\n");
      out.write("\t\t\t\t\t");
      } 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t        <li>\r\n");
      out.write("\t\t\t        \t");
  if(currentPage >= maxPage){  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a>></a>\r\n");
      out.write("\t\t\t\t\t\t");
  }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/qAdminList.qna?currentPage=");
      out.print(currentPage + 1 );
      out.write("'\">></a>\r\n");
      out.write("\t\t\t\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t        </li>\r\n");
      out.write("\t\t\t        <li><a onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/qAdminList.qna?currentPage=");
      out.print( maxPage );
      out.write("'\">>></a></li>\r\n");
      out.write("\t\t\t      </ul>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("            \r\n");
      out.write("            <fieldset>\r\n");
      out.write("                <!--<label for=\"name\"><input type=\"radio\" name=\"search\" value=\"writer\">작성자</label>\r\n");
      out.write("                <label for=\"title\"><input type=\"radio\" name=\"search\" value=\"title\">제목</label>\r\n");
      out.write("                <label for=\"text\"><input type=\"radio\" name=\"search\" value=\"text\">내용</label>  -->\r\n");
      out.write("                <select id=\"searchCondition\">\r\n");
      out.write("                \t<option>---</option>\r\n");
      out.write("                \t<option value=\"userId\">아이디</option>\r\n");
      out.write("                \t<option value=\"name\">이름</option>\r\n");
      out.write("                \t<option value=\"phone\">전화번호</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <input type=\"text\" id=\"keyword\">\r\n");
      out.write("                <input type=\"button\" id=\"searchBtn\" value=\"검색\">\r\n");
      out.write("            </fieldset>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t<script>  \r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#listArea td\").mouseenter(function(){\r\n");
      out.write("\t\t\t\t$(this).parent().css({\"background\":\"lightgray\", \"cursor\":\"pointer\"});\r\n");
      out.write("\t\t\t}).mouseout(function(){\r\n");
      out.write("\t\t\t\t$(this).parent().css({\"background\":\"white\"});\r\n");
      out.write("\t\t\t}).click(function(){\r\n");
      out.write("\t\t\t\tvar qno = $(this).parent().children().eq(0).text();\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/qAdminSelect.qna?qno=\" + qno;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#searchBtn').click(function(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/mAdminSearch.me?con=\"+$('#searchCondition').val()+\"&keyword=\"+$('#keyword').val();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
