/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-26 19:05:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.semi.shop.model.vo.*;
import com.kh.semi.member.model.vo.*;
import java.util.ArrayList;
import com.kh.semi.shop.model.vo.Shop;
import com.kh.semi.member.model.vo.*;

public final class mypagePerson_005f5_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1582645757249L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1582645755766L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.kh.semi.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.kh.semi.shop.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.semi.shop.model.vo.Shop");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 ArrayList<MemberReservationList> mrList = (ArrayList<MemberReservationList>)request.getAttribute("mrList"); 
   ArrayList<Shop> fsList = (ArrayList<Shop>)request.getAttribute("fsList");
	/* Shop se = (Shop)session.getAttribute("selectShop"); */
   /* ArrayList<Shop> mList = (ArrayList<Shop>)session.getAttribute("selectShop");  */

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>마이페이지(개인)</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/siktam/resources/css/headerfooterLayout.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/siktam/resources/css/mypage_person_5.css\">\r\n");
      out.write("    <!-- <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script> -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("    \t$(function(){\r\n");
      out.write("    \t\t$.ajax({\r\n");
      out.write("    \t\t\turl:\"/siktam/shopRecentRecord.sr\",\r\n");
      out.write("    \t\t\ttype:\"get\",\r\n");
      out.write("    \t\t\tsuccess:function(data){\r\n");
      out.write("    \t\t\t\tconsole.log(data);\r\n");
      out.write("    \t\t\t\tvar $content3 = $('#content3');\r\n");
      out.write("    \t\t\t\tvar $recent = $('.recent');\r\n");
      out.write("    \t\t\t\tvar $ul = $('<ul>');\r\n");
      out.write("    \t\t\t\t$.each(data,function(index,value){\r\n");
      out.write("\t    \t\t\t\tvar $li = $('<li>');\r\n");
      out.write("\t    \t\t\t\tvar $recentDiv = $('<div class=\"registStore2\" id=\"recentDiv\">');\r\n");
      out.write("\t    \t\t\t\tvar $imgArea = $('<img src=\"\" class=\"registStoreImg\" alt=\"\" width=\"170px\" height=\"120px\"><br>').text(value.shopImg);\r\n");
      out.write("\t    \t\t\t\tvar $h4 = $('<h4 align=\"center\">').text(value.shopName);\r\n");
      out.write("\t    \t\t\t\tvar $p = $('<p align=\"center\" style=\"word-break: keep-all;\">');\r\n");
      out.write("\t    \t\t\t\tvar $small = $('<small>').text(value.sAddr);\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("\t    \t\t\t\t$content3.append($recent);\r\n");
      out.write("\t    \t\t\t\t$recent.append($ul);\r\n");
      out.write("\t    \t\t\t\t$ul.append($li);\r\n");
      out.write("\t    \t\t\t\t$li.append($recentDiv);\r\n");
      out.write("\t    \t\t\t\t$recentDiv.append($imgArea);\r\n");
      out.write("\t    \t\t\t\t$recentDiv.append($h4);\r\n");
      out.write("\t    \t\t\t\t$recentDiv.append($p);\r\n");
      out.write("\t    \t\t\t\t$p.append($small);\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t});\r\n");
      out.write("    \t\t\t},error:function(){\r\n");
      out.write("    \t\t\t\tconsole.log(\"오류에요\");\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t});\t\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- 헤더 시작 -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member m = (Member)session.getAttribute("member");
	ArrayList<Shop> slist=new ArrayList<Shop>();
	if(m!=null&&m.getShopYN().equals("Y")){
		slist=(ArrayList<Shop>)session.getAttribute("shop");		
	}else{
		slist=null;
	}
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <nav id=\"nav\">\n");
      out.write("    \t<div id=\"logodiv\"><a href=\"/siktam/listMain.ma\"><img id=\"logo\" src=\"/siktam/resources/images/KakaoTalk_20200101_193858750.png\" alt=\"\" style=\"width:50px; height:50px; margin-top:10px;\"></a></div>\r\n");
      out.write("\r\n");
      out.write("    \t<div id=\"navp\">\r\n");
      out.write("\t        ");
 if(m!=null && m.getUserId().equals("4dich")){ 
      out.write("\r\n");
      out.write("\t        \t<a class=\"navp\" href=\"/siktam/views/admin_main_4.jsp\"><span>관리자</span></a>\r\n");
      out.write("\t        ");
 } 
      out.write("\r\n");
      out.write("            <a class=\"navp\" href=\"/siktam/nselectList.no\"><span>공지사항</span></a>\r\n");
      out.write("            <a class=\"navp\" href=\"/siktam/QnaListServlet\"><span>문의사항</span></a>\r\n");
      out.write("            ");
if(m==null) {
      out.write("\r\n");
      out.write("            ");
}else if(m.getShopYN().equals("N")){
      out.write("\r\n");
      out.write("            \t<a class=\"navp\" href=\"/siktam/mypageMember.mm\"><span>마이페이지</span></a>\r\n");
      out.write("            ");
}else{ 
      out.write("\r\n");
      out.write("            \t<a class=\"navp\" href=\"/siktam/views/mypageShop_5.jsp\"><span>마이페이지</span></a>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            ");
 if(m==null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<a class=\"navp\" href=\"/siktam/views/login_2.jsp\"><span style=\"border: 2px solid rgb(13, 78, 100); color:rgb(13, 78, 100); background-color:white; padding:5px\">로그인</span></a>\r\n");
      out.write("            ");
 }else{ 
      out.write("\r\n");
      out.write("            \t<a class=\"navp\" onclick=\"location.href='/siktam/logout.do'; alert('로그아웃되었습니다')\"><span style=\"cursor: pointer; border: 2px solid rgb(13, 78, 100); color:rgb(13, 78, 100); background-color:white; padding:5px\">로그아웃</span></a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 이 안에 작업하기 -->\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("        <div class =\"content\" id=\"content1\">\r\n");
      out.write("            <h1 align=\"center\">마이페이지_개인</h1><br>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div id=\"imgDiv\"><div id=\"storeImg\"></div></div>\r\n");
      out.write("            <div id=\"storeInfo1\">\r\n");
      out.write("                <ul class=\"storeInfo2\">\r\n");
      out.write("                    <li id=\"userName\"><b>");
      out.print( m.getName() );
      out.write("</b>님 안녕하세요</li>\r\n");
      out.write("                    <li><b>내 프로필</b>\r\n");
      out.write("                    <a href=\"views/registerPerson_5_7.jsp\"><input type=\"button\" class=\"btn1\" value=\"수정하기\"></a></li><hr>\r\n");
      out.write("                    <li><b>예약 내역</b>\r\n");
      out.write("                    <input type=\"button\" id=\"userReserve\" class=\"btn1\" value=\"수정하기\" onclick=\"test1();\"></li><hr>\r\n");
      out.write("                    <li><b>결제 내역</b>\r\n");
      out.write("                    <input type=\"button\" class=\"btn1\" value=\"확인하기\" onclick=\"test3();\"></li><hr>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- <form action=\"/siktam/selectUserReserv.re\" method=\"post\"> -->\r\n");
      out.write("        <div id=\"modal1\">\r\n");
      out.write("            <div class=\"modal_content\">\r\n");
      out.write("                <h2>예약 내역</h2>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <table id=\"reservationTb1\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr class=\"reservationTr\">\r\n");
      out.write("                            <th>매장명</th>\r\n");
      out.write("                            <th>예약날짜</th>\r\n");
      out.write("                            <th>예약시간</th> \r\n");
      out.write("                            <th>예약메뉴</th> \r\n");
      out.write("                            <th>예약상태</th> \r\n");
      out.write("                         </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                      ");
for(MemberReservationList rr : mrList){ 
      out.write("\r\n");
      out.write("\t                        <tr class=\"reservationTr\">\r\n");
      out.write("\t                        \t<input type=\"hidden\" class=\"reserveNo\" value=\"");
      out.print(rr.getResNo() );
      out.write("\" />\r\n");
      out.write("\t                        \t<input type=\"hidden\" class=\"shopPid\" value=\"");
      out.print(rr.getShopPid() );
      out.write("\" />\r\n");
      out.write("\t                            <td>");
      out.print(rr.getShopName() );
      out.write("</td>\r\n");
      out.write("\t                            <td>");
      out.print(rr.getrDate() );
      out.write("</td>\r\n");
      out.write("\t                            <td>");
      out.print(rr.getrTime() );
      out.write("</td>\r\n");
      out.write("\t                            <td >");
      out.print(rr.getmNo() );
      out.write("</td>\r\n");
      out.write("\t                            ");
if(rr.getAcceptYN().equals("W")){ 
      out.write("\r\n");
      out.write("\t                            <td>대기중</td>\r\n");
      out.write("\t                            ");
} else if(rr.getAcceptYN().equals("Y")){
      out.write("\r\n");
      out.write("\t                            <td>예약확정</td>\r\n");
      out.write("\t                            ");
} else { 
      out.write("\r\n");
      out.write("\t                            <td>예약거절</td>\r\n");
      out.write("\t                            ");
} 
      out.write("\r\n");
      out.write("<!-- \t                            변경 클릭 시 예약변경 페이지로 이동\r\n");
      out.write("\t                            <td colspan=\"2\">\r\n");
      out.write("\t                            \t<td colspan=\"2\"><input type=\"button\" value=\"변경\" class=\"confirm\" id=\"change\" onclick=\"modify();\"> &nbsp;\r\n");
      out.write("\t                            \t<input type=\"button\" value=\"변경\" class=\"confirm\" id=\"change\"> &nbsp;\r\n");
      out.write("\t                            \t<input type=\"button\" value=\"취소\" class=\"cancel\" id=\"cancel\">\r\n");
      out.write("\t                            </td> -->\r\n");
      out.write("\t                        </tr>\r\n");
      out.write("                       ");
 } 
      out.write("\r\n");
      out.write("                                      \r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <button id=\"modal_close_btn1\" onclick=\"test2();\">창 닫기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal_layer\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- </form> -->\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div id=\"modal2\">\r\n");
      out.write("            <div class=\"modal_content\">\r\n");
      out.write("                <h2>결제 내역</h2>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <table id=\"reservationTb2\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr class=\"reservationTr\">\r\n");
      out.write("                            <th>매장명</th>\r\n");
      out.write("                            <th>메뉴</th> \r\n");
      out.write("                            <th>결제금액</th>  \r\n");
      out.write("                            <th>결제방식</th>  \r\n");
      out.write("                         </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                    \r\n");
      out.write("                    \t");
for(MemberReservationList rp : mrList){ 
      out.write("\r\n");
      out.write("                    \t");
if(rp.getTotalPay()!=0){ 
      out.write("\r\n");
      out.write("                        <tr class=\"reservationTr\">\r\n");
      out.write("                            <td>");
      out.print(rp.getShopName() );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(rp.getmNo() );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(rp.getTotalPay() );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(rp.getPayType() );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
}  
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                       \r\n");
      out.write("                        \r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <button id=\"modal_close_btn2\" onclick=\"test4();\">창 닫기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal_layer\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            function test1(){\r\n");
      out.write("                document.getElementById('modal1').style.display = \"block\";\r\n");
      out.write("                document.getElementById('content2').style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function test2(){\r\n");
      out.write("                document.getElementById('modal1').style.display = \"none\";\r\n");
      out.write("                document.getElementById('content2').style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function test3(){\r\n");
      out.write("                document.getElementById('modal2').style.display = \"block\";\r\n");
      out.write("                document.getElementById('content2').style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("            function test4(){\r\n");
      out.write("                document.getElementById('modal2').style.display = \"none\";\r\n");
      out.write("                document.getElementById('content2').style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            $(\".confirm\").click(function(){\r\n");
      out.write("            \tvar reserveNo = $(this).parent().siblings(\":eq(0)\").val();\r\n");
      out.write("            \t/* console.log(reserveNo); */\r\n");
      out.write("            \t\r\n");
      out.write("            \tvar shopPid = $(this).parent().siblings(\":eq(1)\").val();\r\n");
      out.write("            \t/* console.log(shopPid); */\r\n");
      out.write("            \tlocation.href=\"/siktam/reserveModify.rm?reserveNo=\"+reserveNo+\"&shopPid=\"+shopPid;\r\n");
      out.write("            });\r\n");
      out.write("             \r\n");
      out.write("             $(\".cancel\").click(function(){\r\n");
      out.write("            \t var reserveNo = $(this).parent().siblings(\":eq(0)\").val();\r\n");
      out.write("             \t/* console.log(reserveNo); */\r\n");
      out.write("             \t\r\n");
      out.write("             \tvar shopPid = $(this).parent().siblings(\":eq(1)\").val();\r\n");
      out.write("             \t/* console.log(shopPid); */\r\n");
      out.write("             \t\r\n");
      out.write("            \t var confirmAlert = confirm(\"예약을 취소하시겠습니까?\");\r\n");
      out.write("            \t if(confirmAlert == true){\r\n");
      out.write("            \t\t location.href=\"/siktam/reserveModifyDelete.rm?reserveNo=\"+reserveNo+\"&shopPid=\"+shopPid;\r\n");
      out.write("            \t }\r\n");
      out.write("            \t else if(confirmAlert == false){\r\n");
      out.write("            \t   self.close();\r\n");
      out.write("            \t }\r\n");
      out.write("             \t\r\n");
      out.write("             })\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            /*예약내역 ajax\r\n");
      out.write("             DB에서 값은 넘어오는데 출력이 안됨\r\n");
      out.write("            */\r\n");
      out.write("            /*\r\n");
      out.write("            $('#userReserve').click(function(){\r\n");
      out.write("            \t$.ajax({\r\n");
      out.write("            \t\turl:\"/siktam/selectUserReserv.re\",\r\n");
      out.write("            \t\ttype:\"get\",\r\n");
      out.write("            \t\t dataType : \"json\", \r\n");
      out.write("            \t\tsuccess:function(data){\r\n");
      out.write("            \t\t\tconsole.log(data);\r\n");
      out.write("            \t\t\t$.each(data,function(index,value){\r\n");
      out.write("            \t\t\t\tvar $tr = $('<tr>');\r\n");
      out.write("            \t\t\t\tvar $shopName = $('<td>').text(value.shopName);\r\n");
      out.write("            \t\t\t\tvar $rDate = $('<td>').text(value.rDate);\r\n");
      out.write("            \t\t\t\tvar $rTime = $('<td>').text(value.rTime);\r\n");
      out.write("            \t\t\t\tvar $menu = $('<td>').text(value.menu);\r\n");
      out.write("            \t\t\t\tvar $acceptYn = $('<td>').text(value.acceptYn);\r\n");
      out.write("            \t\t\t\tvar $aa = $('<td>').text(value.acceptYn);\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\t$tr.append($shopName);\r\n");
      out.write("            \t\t\t\t$tr.append($rDate);\r\n");
      out.write("            \t\t\t\t$tr.append($rTime);\r\n");
      out.write("            \t\t\t\t$tr.append($menu);\r\n");
      out.write("            \t\t\t\t$tr.append($acceptYn);\r\n");
      out.write("            \t\t\t\t$tr.append($aa);\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\t$('#reservationTb1').append($tr);\r\n");
      out.write("            \t\t\t});\r\n");
      out.write("            \t\t}, error:function(data){\r\n");
      out.write("            \t\t\tconsole.log(\"에러입니다.\");\r\n");
      out.write("            \t\t}\r\n");
      out.write("            \t});\r\n");
      out.write("            });\r\n");
      out.write("           */\r\n");
      out.write("        </script>\r\n");
      out.write("       \t \r\n");
      out.write("\t\t<!-- <form action=\"/siktam/mypageFavorite.mf\" method=\"post\"> -->\r\n");
      out.write("        <div class =\"content\" id=\"content2\">\r\n");
      out.write("            <h3 id=\"contentTxt\" align=\"left\">내가 즐겨찾기 한 음식점</h3>\r\n");
      out.write("            <div id=\"registStore\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                 ");
for(Shop s : fsList){ 
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"registStore2\" onclick=\"location.href='productDetailPage_6.jsp'\">\r\n");
      out.write("                        \t<input type=\"hidden\" id=\"shopPid\" value=\"");
      out.print( s.getShopPid() );
      out.write("\"/>\r\n");
      out.write("                            <img src=\"");
      out.print(s.getShopImg() );
      out.write("\" class=\"registStoreImg\" alt=\"\" width=\"170px\" height=\"120px\"><br>\r\n");
      out.write("                            <h4 align=\"center\">");
      out.print(s.getShopName() );
      out.write("</h4>\r\n");
      out.write("                            <p align=\"center\"><small>");
      out.print(s.getsAddr() );
      out.write("</small></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"bookmark\">\r\n");
      out.write("                        <p class=\"star\" style=\"color:rgb(255, 184, 53)\">★</a>\r\n");
      out.write("                        </div>                        \r\n");
      out.write("                    </li>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("           </div>\r\n");
      out.write("          <!-- </form> -->\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("                  $(document).ready(function(){\r\n");
      out.write("                  \t$('.star').toggle(function(){\r\n");
      out.write("                      $(this).css({'color':'#eee'});\r\n");
      out.write("                      $.ajax({\r\n");
      out.write("                    \t  \turl:\"/siktam/shopDeleteFavorite.si\",\r\n");
      out.write("              \t\t\t\ttype:\"get\",\r\n");
      out.write("              \t\t\t\tdata:{\r\n");
      out.write("              \t\t\t\t\tshopPid : $('#shopPid').val()\r\n");
      out.write("              \t\t\t\t},\r\n");
      out.write("              \t\t\t\tsuccess: function(data){\r\n");
      out.write("              \t\t\t\t\tconsole.log(data);\r\n");
      out.write("              \t\t\t\t},\r\n");
      out.write("              \t\t\t\terror: function(){\r\n");
      out.write("              \t\t\t\t\tconsole.log(\"결과 전송 실패\");\r\n");
      out.write("              \t\t\t\t}\r\n");
      out.write("                      });\r\n");
      out.write("                      },function(){\r\n");
      out.write("                          $(this).css({'color':'rgb(255, 184, 53)'});\r\n");
      out.write("                          $.ajax({\r\n");
      out.write("                      \t  \turl:\"/siktam/shopInsertFavorite.si\",\r\n");
      out.write("  \t          \t\t\t\ttype:\"get\",\r\n");
      out.write("  \t          \t\t\t\tdata:{\r\n");
      out.write("  \t          \t\t\t\t\tshopPid : $('#shopPid').val()\r\n");
      out.write("  \t          \t\t\t\t},\r\n");
      out.write("  \t          \t\t\t\tsuccess: function(data){\r\n");
      out.write("  \t          \t\t\t\t\tconsole.log(data);\r\n");
      out.write("  \t          \t\t\t\t},\r\n");
      out.write("  \t          \t\t\t\terror: function(){\r\n");
      out.write("  \t          \t\t\t\t\tconsole.log(\"결과 전송 실패\");\r\n");
      out.write("  \t          \t\t\t\t}\r\n");
      out.write("                        });\r\n");
      out.write("                       });\r\n");
      out.write("                  });\r\n");
      out.write("            </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class =\"content\" id=\"content3\">\r\n");
      out.write("            <h3 id=\"contentTxt\" align=\"left\">최근 들여다 본 음식점</h3 id=\"contentTxt\">\r\n");
      out.write("                \r\n");
      out.write("            \r\n");
      out.write("                <div id=\"registStore\" class=\"recent\">\r\n");
      out.write("                 \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("            \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- 푸터 시작 -->\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<footer>\r\n");
      out.write("    <div id=\"footerArea\">\r\n");
      out.write("    <p>\r\n");
      out.write("\t\t<b>식탐</b><br>\r\n");
      out.write("\t\t서울시 강남구 역상동 테헤란로 12길 남도빌딩 kh정보교육원 3층 h클래스 <br>\r\n");
      out.write("\t\t대표자 : 상또두리 | 사업자 등록번호 : 328478-24-2348971<br>\r\n");
      out.write("\t\t전화 : 010365656 | 팩스 : 0236541255| honbabsiktam.co.kr<br>\r\n");
      out.write("        <b>Copyright ⓒ 식탐 All rights reserved</b>\r\n");
      out.write("    </p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
