/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-25 15:55:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.semi.pay.model.vo.*;
import com.kh.semi.coupon.model.vo.*;
import java.util.*;
import java.util.ArrayList;
import com.kh.semi.shop.model.vo.Shop;
import com.kh.semi.member.model.vo.*;

public final class pay_005f5_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1582645757249L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1582645755766L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.kh.semi.pay.model.vo");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.kh.semi.coupon.model.vo");
    _jspx_imports_packages.add("com.kh.semi.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.semi.shop.model.vo.Shop");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
Coupon c = (Coupon)request.getAttribute("c");
      ArrayList<PayInfo>list = (ArrayList<PayInfo>)request.getAttribute("list");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>pay5</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/siktam/resources/css/headerfooterLayout.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/siktam/resources/css/pay_5.css\">\r\n");
      out.write("    <script src=\"/siktam/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- 헤더 시작 -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member m = (Member)session.getAttribute("member");
	ArrayList<Shop> slist=new ArrayList<Shop>();
	if(m!=null&&m.getShopYN().equals("Y")){
		slist=(ArrayList<Shop>)session.getAttribute("shop");		
	}else{
		slist=null;
	}
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <nav id=\"nav\">\n");
      out.write("    \t<div id=\"logodiv\"><a href=\"/siktam/listMain.ma\"><img id=\"logo\" src=\"/siktam/resources/images/KakaoTalk_20200101_193858750.png\" alt=\"\" style=\"width:50px; height:50px; margin-top:10px;\"></a></div>\r\n");
      out.write("\r\n");
      out.write("    \t<div id=\"navp\">\r\n");
      out.write("\t        ");
 if(m!=null && m.getUserId().equals("4dich")){ 
      out.write("\r\n");
      out.write("\t        \t<a class=\"navp\" href=\"/siktam/views/admin_main_4.jsp\"><span>관리자</span></a>\r\n");
      out.write("\t        ");
 } 
      out.write("\r\n");
      out.write("            <a class=\"navp\" href=\"/siktam/nselectList.no\"><span>공지사항</span></a>\r\n");
      out.write("            <a class=\"navp\" href=\"/siktam/QnaListServlet\"><span>문의사항</span></a>\r\n");
      out.write("            ");
if(m==null) {
      out.write("\r\n");
      out.write("            ");
}else if(m.getShopYN().equals("N")){
      out.write("\r\n");
      out.write("            \t<a class=\"navp\" href=\"/siktam/mypageMember.mm\"><span>마이페이지</span></a>\r\n");
      out.write("            ");
}else{ 
      out.write("\r\n");
      out.write("            \t<a class=\"navp\" href=\"/siktam/views/mypageShop_5.jsp\"><span>마이페이지</span></a>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            ");
 if(m==null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<a class=\"navp\" href=\"/siktam/views/login_2.jsp\"><span style=\"border: 2px solid rgb(13, 78, 100); color:rgb(13, 78, 100); background-color:white; padding:5px\">로그인</span></a>\r\n");
      out.write("            ");
 }else{ 
      out.write("\r\n");
      out.write("            \t<a class=\"navp\" onclick=\"location.href='/siktam/logout.do'; alert('로그아웃되었습니다')\"><span style=\"cursor: pointer; border: 2px solid rgb(13, 78, 100); color:rgb(13, 78, 100); background-color:white; padding:5px\">로그아웃</span></a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("<form action=\"/siktam/views/payResult.jsp\" method=\"post\">\r\n");
      out.write("    <!-- 이 안에 작업하기 -->\r\n");
      out.write("    <div id=\"area1\">\r\n");
      out.write("    <div id=\"StoreTitle\">\r\n");
      out.write("        <div id=\"titleImg\">\r\n");
      out.write("            <img src=\"/siktam/resources/images/udon.png\" alt=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"titleText\">\r\n");
      out.write("            <h1><b>");
      out.print( list.get(0).getRshopName() );
      out.write("</b>(결제하기)</h1>\r\n");
      out.write("            <p>");
      out.print( list.get(0).getRshopAddr() );
      out.write("</p>\r\n");
      out.write("            <input type=hidden id=\"rNo\" name=\"rNo\" value=");
      out.print(list.get(0).getrNo());
      out.write(">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("        <div id=\"contentBox\">    \r\n");
      out.write("            <div id=\"content1\" class=\"content\">\r\n");
      out.write("                <div id=\"content1-1\">\r\n");
      out.write("                    <div id=\"title\">\r\n");
      out.write("                        <p class=\"title-1\"><b>결제하기</b></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"sub-title\">\r\n");
      out.write("                        <p class=\"title-1\"><b>결제수단 선택</b></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"sub-sub-title\">온라인 결제</p><hr>\r\n");
      out.write("                    <table >\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th class=\"paytableth\">일반결제</th>\r\n");
      out.write("                                <td class=\"noline\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"creditcard1\" name=\"payType\" class=\"pay\" value=\"cardPay\"><label for=\"creditcard1\">신용카드</label>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th class=\"paytableth\">네이버페이 결제</th>\r\n");
      out.write("                                <td class=\"noline\">\r\n");
      out.write("                                    <label for=\"creditcard2\"><input type=\"radio\" id=\"creditcard2\" name=\"payType\" value=\"naverPay\" class=\"pay\">\r\n");
      out.write("                                    <img src=\"/siktam/resources/images/네이버페이_로고_(800px_X_400px).jpg\" id=\"naver\" alt=\"네이버페이로고\"></label>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th class=\"paytableth\">카카오페이 결제</th>\r\n");
      out.write("                                <td class=\"noline\">\r\n");
      out.write("                                    <label for=\"creditcard3\"><input type=\"radio\" id=\"creditcard3\" name=\"payType\" value=\"kakaoPay\" class=\"pay\">\r\n");
      out.write("                                    <img src=\"/siktam/resources/images/카카오페이.png\"  id=\"kakao\" alt=\"카카오페이\"></label>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"content1-2\">\r\n");
      out.write("                <div id=\"sub-title\">\r\n");
      out.write("                    <p class=\"title-1\"><b>마일리지 사용</b></p>\r\n");
      out.write("                </div>    \r\n");
      out.write("                    <div id=\"mileageDiv\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <input type=\"text\" class=\"mileage\" id=\"useMile\" name=\"mileage\" value=\"0\"><label id=\"won1\">원 <--</label>\r\n");
      out.write("                            <input type=\"text\" class=\"mileage\" id=\"getMile\" name=\"getMile\" value='");
      out.print( m.getMileage() );
      out.write("' style=\"text-align: left;\"><label id=\"won2\">원</label>\r\n");
      out.write("                        \t<p>(사용가능 마일리지)</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button type=\"button\" id=\"appliance\" >적용</button>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"content1-3\">\r\n");
      out.write("                    <div id=\"sub-title\">\r\n");
      out.write("                        <p class=\"title-1\"><b>할인쿠폰 선택</b></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"text\" list=\"mylist\" id=\"coupon\" value=\"0\" style=\"width: 75%;height: 30px;font-size: 15px;\">\r\n");
      out.write("                    <input type=\"hidden\" list=\"mylist\" id=\"coupon\" name=\"couponNo\" value='");
      out.print(c.getCouponNo() );
      out.write("' style=\"width: 75%;height: 30px;font-size: 15px;\">\r\n");
      out.write("                    <datalist id=\"mylist\">\r\n");
      out.write("                        <option value=\"0\">쿠폰 없음</option>\r\n");
      out.write("                        <option value='");
      out.print(c.getDiscount() );
      out.write('\'');
      out.write('>');
      out.print(c.getCouponName() );
      out.write("</option>\r\n");
      out.write("                    </datalist>\r\n");
      out.write("                    <button type=\"button\" id=\"couponclick\">적용</button>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("            <div id=\"content2\" class=\"content\">\r\n");
      out.write("                <div id=\"content1-1\">\r\n");
      out.write("                    <div id=\"sub-title\">\r\n");
      out.write("                        <p class=\"title-1\"><b>주문내역</b></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"sub-sub-title2\">\r\n");
      out.write("                        <p class=\"title-1\"><b>");
      out.print( list.get(0).getRshopName() );
      out.write("</b></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"menulist\">\r\n");
      out.write("                        <table id=\"menutable\" >\r\n");
      out.write("                        ");
for(PayInfo pi : list){ 
      out.write("\r\n");
      out.write("                            <tr class=\"menupan\">\r\n");
      out.write("                                <td class=\"menu\">");
      out.print( pi.getRmenuName() );
      out.write(' ');
      out.write('X');
      out.write(' ');
      out.print( pi.getRmenuCount());
      out.write("개</td>\r\n");
      out.write("                                <td>");
      out.print( pi.getRmenuPrice() );
      out.write("</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        ");
} 
      out.write("    \r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <table id=\"menutable2\">\r\n");
      out.write("                        <tr class=\"menupan2\">\r\n");
      out.write("                            <td class=\"allpay\"><b>총 결제 금액</b></td>\r\n");
      out.write("                            <td><b>");
      out.print(list.get(0).getTotalPay());
      out.write("</b></td>\r\n");
      out.write("                    \t\t<td><input type=\"hidden\" id=\"total\"name=\"totalPay\" value=\"");
      out.print(list.get(0).getTotalPay());
      out.write("\">\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"content1-4\">\r\n");
      out.write("                  <ul id=\"agree\">\r\n");
      out.write("                      <li><label for=\"all_chk\" class=\"chk_label\" id=\"all_chk\"><input type=\"checkbox\" id=\"all_chk\" class=\"chk\" onclick=\"allselect(this.checked)\">전체동의</label><a href=\"termsOfUse2_5.jsp\" target=\"_blank\"><small>내용보기</small></a></li><hr>\r\n");
      out.write("                      <li><label for=\"sms_agree\" class=\"chk_label\"><input type=\"checkbox\" id=\"sms_agree\" name=\"agree\" class=\"chk\">SMS 수신동의</label></li>\r\n");
      out.write("                      <li><label for=\"use_agree\" class=\"chk_label\"><input type=\"checkbox\" id=\"use_agree\" name=\"agree\" class=\"chk\">이용약관 동의(필수)</label><a href=\"termsOfUse2_5.jsp\" target=\"_blank\"><small>내용보기</small></a></li>\r\n");
      out.write("                      <li><label for=\"collect_chk\" class=\"chk_label\"><input type=\"checkbox\" id=\"collect_agree\" name=\"agree\" class=\"chk\">개인정보 수집 및 이용동의(필수)</label><a href=\"termsOfUse2_5.jsp\" target=\"_blank\"><small>내용보기</small></a></li>\r\n");
      out.write("                      <li><label for=\"third_agree\" class=\"chk_label\"><input type=\"checkbox\" id=\"third_agree\" name=\"agree\" class=\"chk\">개인정보 제3자 제공동의(필수)</label><a href=\"termsOfUse2_5.jsp\" target=\"_blank\"><small>내용보기</small></a></li>\r\n");
      out.write("                      <li><label for=\"electronic_agree\" class=\"chk_label\"><input type=\"checkbox\" id=\"electronic_agree\" name=\"agree\" class=\"chk\">전자금융거래 이용약관(필수)</label><a href=\"termsOfUse2_5.jsp\" target=\"_blank\"><small>내용보기</small></a></li>\r\n");
      out.write("                      <li><label for=\"fourteen_agree\" class=\"chk_label\"><input type=\"checkbox\" id=\"fourteen_agree\" name=\"agree\" class=\"chk\">만 14세 이상 사용자(필수)</label><a href=\"termsOfUse2_5.jsp\" target=\"_blank\"><small>내용보기</small></a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <input type=\"submit\" id=\"payment\" value=\"결제하기\">\r\n");
      out.write("                  <input type=\"button\" id=\"payment\" name=\"cancle\" value=\"취소하기\" onclick=\"location.href = 'reservationdelete.rc'\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    <script>\r\n");
      out.write("    \t$('input[name=\"cancle\"]').click(function(){\r\n");
      out.write("    \t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/reservationdelete.rc?rNo=\"+'");
      out.print(list.get(0).getrNo());
      out.write("'\r\n");
      out.write("    \t});\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    \t$('#couponclick').click(function(){\r\n");
      out.write("    \t\tvar coupon = $('#coupon').val();\r\n");
      out.write("    \t\tvar useMile = $('#useMile').val();\r\n");
      out.write("\t\t\tvar getMile = '");
      out.print(c.getMileage());
      out.write("'\r\n");
      out.write("    \t\tvar total = ");
      out.print(list.get(0).getTotalPay());
      out.write(";\r\n");
      out.write("    \t\t$.ajax({\r\n");
      out.write("    \t\t\turl:\"/siktam/coupon.cc\",\r\n");
      out.write("    \t\t\ttype:\"get\",\r\n");
      out.write("    \t\t\tdata:{\r\n");
      out.write("    \t\t\t\t\"coupon\" : coupon,\r\n");
      out.write("    \t\t\t\t\"useMile\" : useMile,\r\n");
      out.write("\t\t\t\t\t\"getMile\" : getMile,\r\n");
      out.write("    \t\t\t\t\"total\" : total\r\n");
      out.write("    \t\t\t},success:function(data){\r\n");
      out.write("    \t\t\t\tconsole.log(data);\r\n");
      out.write("    \t\t\t\t$('#menutable2').find('tr').remove();\r\n");
      out.write("    \t\t\t\tvar $b1 = $('<b>').text(\"총 결제 금액\");\r\n");
      out.write("    \t\t\t\tvar $b2 = $('<b>').text(data.totalPay);\r\n");
      out.write("    \t\t\t\tvar $td0 = $('<td class=\"allpay\">');\r\n");
      out.write("    \t\t\t\tvar $td1 = $('<td>');\r\n");
      out.write("    \t\t\t\tvar $td2 = $('<td>');\r\n");
      out.write("    \t\t\t\tvar $tr = $('<tr>');\r\n");
      out.write("    \t\t\t\tvar $input = $('<input type=\"hidden\" id=\"total\"name=\"totalPay\" value=\"'+data.totalPay+'\">');\r\n");
      out.write("    \t\t\t\t$td0.append($b1);\r\n");
      out.write("    \t\t\t\t$td1.append($b2);\r\n");
      out.write("    \t\t\t\t$td2.append($input);\r\n");
      out.write("    \t\t\t\t$tr.append($td0).append($td1).append($td2);\r\n");
      out.write("    \t\t\t\t$('#menutable2').append($tr)\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\tconsole.log($('#total').val());\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t});\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t$('#appliance').click(function(){\r\n");
      out.write("\t\t\tvar coupon = $('#coupon').val();\r\n");
      out.write("    \t\tvar useMile = $('#useMile').val();\r\n");
      out.write("\t\t\tvar getMile = '");
      out.print(c.getMileage());
      out.write("'\r\n");
      out.write("    \t\tvar total = ");
      out.print(list.get(0).getTotalPay());
      out.write(";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"/siktam/coupon.cc\",\r\n");
      out.write("\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\"coupon\" : coupon,\r\n");
      out.write("\t\t\t\t\t\"useMile\" : useMile,\r\n");
      out.write("\t\t\t\t\t\"getMile\" : getMile,\r\n");
      out.write("\t\t\t\t\t\"total\" : total\r\n");
      out.write("\t\t\t\t},success:function(data){\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\tif(data.useMile <= data.getMile && data.useMile <= data.totalPay){\r\n");
      out.write("\t\t\t\t\t\t$('#menutable2').find('tr').remove();\r\n");
      out.write("    \t\t\t\t\t$('#mileageDiv').find('div').remove();\r\n");
      out.write("        \t\t\t\tvar $b1 = $('<b>').text(\"총 결제 금액\");\r\n");
      out.write("        \t\t\t\tvar $b2 = $('<b>').text(data.totalPay);\r\n");
      out.write("        \t\t\t\tvar $td0 = $('<td class=\"allpay\">');\r\n");
      out.write("        \t\t\t\tvar $td1 = $('<td>');\r\n");
      out.write("        \t\t\t\tvar $td2 = $('<td>');\r\n");
      out.write("        \t\t\t\tvar $tr = $('<tr>');\r\n");
      out.write("        \t\t\t\tvar $input = $('<input type=\"hidden\" id=\"total\"name=\"totalPay\" value=\"'+data.totalPay+'\">');\r\n");
      out.write("        \t\t\t\t$td0.append($b1);\r\n");
      out.write("        \t\t\t\t$td1.append($b2);\r\n");
      out.write("        \t\t\t\t$td2.append($input);\r\n");
      out.write("        \t\t\t\t$tr.append($td0).append($td1).append($td2);\r\n");
      out.write("        \t\t\t\t$('#menutable2').append($tr)\r\n");
      out.write("\t    \t\t\t\t\r\n");
      out.write("    \t\t\t\t\tvar $div = $('<div>');\r\n");
      out.write("\t    \t\t\t\tvar $usemile = $('<input type=\"text\" class=\"mileage\" id=\"useMile\" name=\"useMile\" value=\"'+data.useMile+'\">');\r\n");
      out.write("\t    \t\t\t\tvar $label = $('<label id=\"won1\">').text(\"원 <--\");\r\n");
      out.write("\t    \t\t\t\tvar $mile = $('<input type=\"text\" class=\"mileage\" id=\"getMile\" name=\"getMile\" value=\"'+data.mile+'\" style=\"text-align: left;\">');\r\n");
      out.write("\t    \t\t\t\tvar $label2 = $('<label id=\"won2\">').text(\"원\");\r\n");
      out.write("\t    \t\t\t\tvar $p = $('<p>').text(\"(사용가능 마일리지)\");\r\n");
      out.write("\t    \t\t\t\t\r\n");
      out.write("\t    \t\t\t\t$div.append($usemile);\r\n");
      out.write("\t    \t\t\t\t$div.append($label);\r\n");
      out.write("\t    \t\t\t\t$div.append($mile);\r\n");
      out.write("\t    \t\t\t\t$div.append($label2);\r\n");
      out.write("\t    \t\t\t\t$div.append($p)\r\n");
      out.write("\t    \t\t\t\t$('#mileageDiv').append($div);\r\n");
      out.write("    \t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\talert(\"마일리지 다시입력\");\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("    <script>\r\n");
      out.write("     \r\n");
      out.write("    // 전체동의 체크박스\r\n");
      out.write("        function allselect(chd) {\r\n");
      out.write("            var agree = document.getElementsByName(\"agree\");\r\n");
      out.write("            for (var i = 0; i < agree.length; i++) {\r\n");
      out.write("                agree[i].checked = chd;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("       /*  function newOpen(){\r\n");
      out.write("            var popupX = (document.body.offsetWidth / 2) - (200 / 2);// 초기값 var popupX = (document.body.offsetWidth / 2) - (200 / 2);\r\n");
      out.write("            var popupY = (document.body.offsetHeight / 2);\r\n");
      out.write("        \r\n");
      out.write("        window.open('payPrint_1.jsp','예약완료','width=1000px, height=800px, scrollbars= no, toolbar=no, menubar=no,location=no,left='+ popupX + ', top='+ popupY+\"'\");\r\n");
      out.write("        } */\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <!-- 푸터 시작 -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<footer>\r\n");
      out.write("    <div id=\"footerArea\">\r\n");
      out.write("    <p>\r\n");
      out.write("\t\t<b>식탐</b><br>\r\n");
      out.write("\t\t서울시 강남구 역상동 테헤란로 12길 남도빌딩 kh정보교육원 3층 h클래스 <br>\r\n");
      out.write("\t\t대표자 : 상또두리 | 사업자 등록번호 : 328478-24-2348971<br>\r\n");
      out.write("\t\t전화 : 010365656 | 팩스 : 0236541255| honbabsiktam.co.kr<br>\r\n");
      out.write("        <b>Copyright ⓒ 식탐 All rights reserved</b>\r\n");
      out.write("    </p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
