/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-27 11:42:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.kh.semi.review.model.vo.*;
import java.util.ArrayList;
import com.kh.semi.shop.model.vo.Shop;
import com.kh.semi.member.model.vo.*;

public final class productReviewPage_005f7_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1582645757249L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1582645755766L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.kh.semi.review.model.vo");
    _jspx_imports_packages.add("com.kh.semi.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.semi.shop.model.vo.Shop");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	ArrayList<Review> rList = (ArrayList<Review>)request.getAttribute("reviewList"); 
	ArrayList<Review> allReviewList = (ArrayList<Review>)request.getAttribute("allReviewList"); 
	Shop s = (Shop)request.getAttribute("shop");
	PageInfo pi = (PageInfo)request.getAttribute("pi");
	ReviewScore rScore = (ReviewScore)request.getAttribute("ReviewScore");
	int listCount = pi.getListCount();
	int currentPage = pi.getCurrentPage();
	int maxPage = pi.getMaxPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();
	String howSelect = (String)request.getAttribute("howSelect");
	/* Member mem = (Member)session.getAttribute("member"); */

      out.write("   \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>리뷰 페이지</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/siktam/resources/css/headerfooterLayout.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/siktam/resources/css/productReviewPage_7.css\">\r\n");
      out.write("    <script src=\"/siktam/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- 헤더 시작 -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member m = (Member)session.getAttribute("member");
	ArrayList<Shop> slist=new ArrayList<Shop>();
	if(m!=null&&m.getShopYN().equals("Y")){
		slist=(ArrayList<Shop>)session.getAttribute("shop");		
	}else{
		slist=null;
	}
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <nav id=\"nav\">\n");
      out.write("    \t<div id=\"logodiv\"><a href=\"/siktam/listMain.ma\"><img id=\"logo\" src=\"/siktam/resources/images/KakaoTalk_20200101_193858750.png\" alt=\"\" style=\"width:50px; height:50px; margin-top:10px;\"></a></div>\r\n");
      out.write("\r\n");
      out.write("    \t<div id=\"navp\">\r\n");
      out.write("\t        ");
 if(m!=null && m.getUserId().equals("4dich")){ 
      out.write("\r\n");
      out.write("\t        \t<a class=\"navp\" href=\"/siktam/views/admin_main_4.jsp\"><span>관리자</span></a>\r\n");
      out.write("\t        ");
 } 
      out.write("\r\n");
      out.write("            <a class=\"navp\" href=\"/siktam/nselectList.no\"><span>공지사항</span></a>\r\n");
      out.write("            <a class=\"navp\" href=\"/siktam/QnaListServlet\"><span>문의사항</span></a>\r\n");
      out.write("            ");
if(m==null) {
      out.write("\r\n");
      out.write("            ");
}else if(m.getShopYN().equals("N")){
      out.write("\r\n");
      out.write("            \t<a class=\"navp\" href=\"/siktam/mypageMember.mm\"><span>마이페이지</span></a>\r\n");
      out.write("            ");
}else{ 
      out.write("\r\n");
      out.write("            \t<a class=\"navp\" href=\"/siktam/views/mypageShop_5.jsp\"><span>마이페이지</span></a>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            ");
 if(m==null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<a class=\"navp\" href=\"/siktam/views/login_2.jsp\"><span style=\"border: 2px solid rgb(13, 78, 100); color:rgb(13, 78, 100); background-color:white; padding:5px\">로그인</span></a>\r\n");
      out.write("            ");
 }else{ 
      out.write("\r\n");
      out.write("            \t<a class=\"navp\" onclick=\"location.href='/siktam/logout.do'; alert('로그아웃되었습니다')\"><span style=\"cursor: pointer; border: 2px solid rgb(13, 78, 100); color:rgb(13, 78, 100); background-color:white; padding:5px\">로그아웃</span></a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 이 안에 작업하기 -->\r\n");
      out.write("\r\n");
      out.write("    <div id=\"all\"> <!-- 전체 div-->\r\n");
      out.write("        <div class=\"pagemainimg\"><img id=\"shopimg\" src=\"/siktam/resources/images/");
      out.print(s.getShopImg());
      out.write("\"></div>\r\n");
      out.write("        <div class=\"pageselect\">\r\n");
      out.write("            <!-- %% 업체정보연결-->\r\n");
      out.write("            <a href=\"/siktam/sSelect.so?shopPid=");
      out.print(s.getShopPid());
      out.write("\"><div id=\"information\"><span>업체정보</span></div></a>\r\n");
      out.write("            <!-- %% 리뷰연결-->\r\n");
      out.write("            <a href=\"#\"><div id=\"review\"><span>리뷰(");
      out.print( allReviewList.size() );
      out.write(")</span></div></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"pagetop\">\r\n");
      out.write("            <h3>");
      out.print( s.getShopName() );
      out.write("</h3>\r\n");
      out.write("            <span>");
      out.print( s.getsInfo() );
      out.write("</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <h3>매장 평점</h3>\r\n");
      out.write("        <hr>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"score\"> <!-- 평점 -->\r\n");
      out.write("            <div id=\"number\" class=\"scoreIn\">\r\n");
      out.write("                <h3 id=\"numberScore\">");
      out.print( rScore.getScore() );
      out.write("점</h3><br>\r\n");
      out.write("                <!--<img id=\"scoreNumber\" src=\"/siktam/resources/images/star.png\" alt=\"\">-->\r\n");
      out.write("                <!-- <div class=\"starRev\">\r\n");
      out.write("                    <span class=\"starR on\">별1</span>\r\n");
      out.write("                    <span class=\"starR\">별2</span>\r\n");
      out.write("                    <span class=\"starR\">별3</span>\r\n");
      out.write("                    <span class=\"starR\">별4</span>\r\n");
      out.write("                    <span class=\"starR\">별5</span>\r\n");
      out.write("                </div> -->\r\n");
      out.write("               <p id=\"star_grade\">\r\n");
      out.write("                    <a href=\"#\">★</a>\r\n");
      out.write("                    <a href=\"#\">★</a>\r\n");
      out.write("                    <a href=\"#\">★</a>\r\n");
      out.write("                    <a href=\"#\">★</a>\r\n");
      out.write("                    <a href=\"#\">★</a>\r\n");
      out.write("                </p>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"scores\" class=\"scoreIn\">\r\n");
      out.write("                <h4 class=\"jum\">5점&nbsp;&nbsp;<progress value=\"");
      out.print( rScore.getFive() );
      out.write("\" max=\"");
      out.print( allReviewList.size() );
      out.write("\" class=\"var\"></progress></h4><br>\r\n");
      out.write("                <h4 class=\"jum\">4점&nbsp;&nbsp;<progress value=\"");
      out.print( rScore.getFour() );
      out.write("\" max=\"");
      out.print( allReviewList.size() );
      out.write("\" class=\"var\"></progress></h4><br>\r\n");
      out.write("                <h4 class=\"jum\">3점&nbsp;&nbsp;<progress value=\"");
      out.print( rScore.getThree() );
      out.write("\" max=\"");
      out.print( allReviewList.size() );
      out.write("\" class=\"var\"></progress></h4><br>\r\n");
      out.write("                <h4 class=\"jum\">2점&nbsp;&nbsp;<progress value=\"");
      out.print( rScore.getTwo() );
      out.write("\" max=\"");
      out.print( allReviewList.size() );
      out.write("\" class=\"var\"></progress></h4><br>\r\n");
      out.write("                <h4 class=\"jum\">1점&nbsp;&nbsp;<progress value=\"");
      out.print( rScore.getOne() );
      out.write("\" max=\"");
      out.print( allReviewList.size() );
      out.write("\" class=\"var\"></progress></h4><br>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <h4>리뷰</h4>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("            <div id=\"wReview\">\r\n");
      out.write("                <button id=\"wReviewbtn\">리뷰 작성</button>\r\n");
      out.write("                <p>리뷰 쓰기</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div id=\"select1\"> <!-- 리뷰 시작 -->\r\n");
      out.write("                <label>정렬방식</label> <!-- 리뷰 정렬 방식 선택-->\r\n");
      out.write("                <select id=\"selectArray\" name=\"selectArray\" > <!-- TODO -->\r\n");
      out.write("                    <option value=\"new\">최신순</option>\r\n");
      out.write("                    <option value=\"rowScore\">별점 낮은 순</option>\r\n");
      out.write("                    <option value=\"highScore\">별점 높은 순</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <br>\r\n");
      out.write("\t\t");
 if(m != null){ 
      out.write("\r\n");
      out.write("\t        <div id=\"reviewWriteText\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" enctype=\"multipart/form-data\" id=\"reviewForm\">\r\n");
      out.write("\t            <div class=\"allReview\" id=\"writeReview\">\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t                    <img class=\"id1\" src=\"/siktam/resources/images/person1.png\" alt=\"\">&nbsp;&nbsp;<label class=\"idLabel\">");
      out.print( m.getUserId() );
      out.write("</label>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <br>\r\n");
      out.write("\t                <label>별점 : </label>\r\n");
      out.write("\t                <label id=\"star_grade_review\">\r\n");
      out.write("\t                    <a href=\"#\">★</a>\r\n");
      out.write("\t                    <a href=\"#\">★</a>\r\n");
      out.write("\t                    <a href=\"#\">★</a>\r\n");
      out.write("\t                    <a href=\"#\">★</a>\r\n");
      out.write("\t                    <a href=\"#\">★</a>\r\n");
      out.write("\t                </label>\r\n");
      out.write("\t                <br><br>\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t                    <label>사진 등록 : </label>\r\n");
      out.write("\t                    <label>\r\n");
      out.write("\t                        <input type=\"file\" id=\"ex_file\" accept=\"image/*\" name=\"file\">\r\n");
      out.write("\t                    </label>\r\n");
      out.write("\t                    <br><br>\r\n");
      out.write("\t                    <textarea name=\"rContent\" id=\"reviewText\" cols=\"105\" rows=\"10\" placeholder=\"리뷰를 작성해 주세요\"></textarea>\r\n");
      out.write("\t                    <br>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t                    <button id=\"rwbtn1\" class=\"rwbtn\" style=\"display:none\">리뷰등록</button>\r\n");
      out.write("\t   \t\t\t</form>\r\n");
      out.write("\t   \t\t\t\t\t<button id=\"rwbtn2\" class=\"rwbtn\">작성 여부 확인</button>\r\n");
      out.write("\t        </div>\r\n");
      out.write("        ");
 }
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <br><br><br>\r\n");
      out.write("\r\n");
      out.write("        <!-- 각 버튼은 리뷰 상세를 열고 닫는 버튼 설정 TODO-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"allReview\" id=\"reviewReview\">\r\n");
      out.write("\t\t");
 for(Review r : rList){ 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("            <div class=\"personInfo\">\r\n");
      out.write("                <img class=\"id1\" src=\"/siktam/resources/images/person1.png\" alt=\"\">&nbsp;&nbsp;<label class=\"idLabel\">");
      out.print( r.getUserId() );
      out.write("</label>\r\n");
      out.write("                <div class=\"bottomBtn\">\r\n");
      out.write("                \t<button id=\"btn1\" class=\"reviewBtn\">▼</button>\r\n");
      out.write("                ▼</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"personReview1\" class=\"personReview\">\r\n");
      out.write("            \t<div class=\"scoreScore\" style=\"display : none;\">");
      out.print( r.getScore() );
      out.write("</div>\r\n");
      out.write("                <label>별점 : </label>\r\n");
      out.write("                <label id=\"star_view1\">\r\n");
      out.write("                    <a href=\"#\">★</a>\r\n");
      out.write("                    <a href=\"#\">★</a>\r\n");
      out.write("                    <a href=\"#\">★</a>\r\n");
      out.write("                    <a href=\"#\">★</a>\r\n");
      out.write("                    <a href=\"#\">★</a>\r\n");
      out.write("                </label>\r\n");
      out.write("                \r\n");
      out.write("                ");
 if(m!=null) { 
                	if(m.getUserId().equals(r.getUserId())) {
                
      out.write("\r\n");
      out.write("                <label style=\"display:none\">");
      out.print(r.getrNo() );
      out.write("</label>\r\n");
      out.write("                <button class=\"deleteBtn\"><img src=\"/siktam/resources/images/delete.jpg\" class=\"deleteimg\"></button>\r\n");
      out.write("                ");
 	}
                   }
                
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <br><br>\r\n");
      out.write("                ");
 if(!r.getReviewImg().equals("review.png")) { 
      out.write("\r\n");
      out.write("                <div class=\"imgDiv\">\r\n");
      out.write("                    <img src=\"/siktam/resources/images/");
      out.print(r.getReviewImg() );
      out.write("\" class=\"reviewImg\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                <br>\r\n");
      out.write("                <p style=\"font-size:20px;\">");
      out.print( r.getrContent() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <br>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 페이지 버튼 -->\r\n");
      out.write("        \r\n");
      out.write("         <div class=\"pagingArea\" align=\"center\">\r\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/rPage.ro?shopPid=");
      out.print(s.getShopPid());
      out.write("&currentPage=1&howSelect=");
      out.print(howSelect);
      out.write("'\"><<</button>\r\n");
      out.write("\t\t\t");
  if(currentPage <= 1){ 
      out.write("\r\n");
      out.write("\t\t\t<button disabled><</button>\r\n");
      out.write("\t\t\t");
  }else{ 
      out.write("\r\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/rPage.ro?shopPid=");
      out.print(s.getShopPid());
      out.write("&currentPage=");
      out.print(currentPage - 1 );
      out.write("&howSelect=");
      out.print(howSelect);
      out.write("'\"><</button>\r\n");
      out.write("\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 for(int p = startPage; p <= endPage; p++){
					if(p == currentPage){	
			
      out.write("\r\n");
      out.write("\t\t\t\t<button disabled>");
      out.print( p );
      out.write("</button>\r\n");
      out.write("\t\t\t");
      }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<button onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/rPage.ro?shopPid=");
      out.print(s.getShopPid());
      out.write("&currentPage=");
      out.print( p );
      out.write("&howSelect=");
      out.print(howSelect);
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</button>\r\n");
      out.write("\t\t\t");
      } 
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");
  if(currentPage >= maxPage){  
      out.write("\r\n");
      out.write("\t\t\t<button disabled>></button>\r\n");
      out.write("\t\t\t");
  }else{ 
      out.write("\r\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/rPage.ro?shopPid=");
      out.print(s.getShopPid());
      out.write("&currentPage=");
      out.print(currentPage + 1 );
      out.write("&howSelect=");
      out.print(howSelect);
      out.write("'\">></button>\r\n");
      out.write("\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/rPage.ro?shopPid=");
      out.print(s.getShopPid());
      out.write("&currentPage=");
      out.print( maxPage );
      out.write("&howSelect=");
      out.print(howSelect);
      out.write("'\">>></button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("        <br>\r\n");
      out.write("\t\t\r\n");
      out.write("        <script>\r\n");
      out.write("            $(function(){\r\n");
      out.write("            \t\r\n");
      out.write("            \t");
if(howSelect.equals("rowScore")) {
      out.write("\r\n");
      out.write("\t\t    \t   $(\"#selectArray\").val(\"rowScore\").attr(\"selected\", \"selected\");\r\n");
      out.write("\t    \t\t");
}else if(howSelect.equals("highScore")){
      out.write("\r\n");
      out.write("\t   \t\t\t\t$(\"#selectArray\").val(\"highScore\").attr(\"selected\", \"selected\");\r\n");
      out.write("\t    \t\t");
}
      out.write("\r\n");
      out.write("            \t\r\n");
      out.write("            \t$('#selectArray').on('change',function(){\r\n");
      out.write("\t\t\t\t\tvar selectHow = $(this).val();\r\n");
      out.write("\t\t\t\t\tlocation.href=\"/siktam/rPage.ro?shopPid=");
      out.print(s.getShopPid());
      out.write("&howSelect=\"+selectHow;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("            \t\r\n");
      out.write("            \t$('#star_grade_review a').click(function(event){\r\n");
      out.write("            \t\t\r\n");
      out.write("            \t\tevent.preventDefault ? event.preventDefault() : (event.returnValue = false);\r\n");
      out.write("            \t\t\r\n");
      out.write("            \t\t$(this).parent().children('a').removeClass('on');\r\n");
      out.write("            \t\t$(this).addClass('on').prevAll('a').addClass('on');\r\n");
      out.write("            \t\t\r\n");
      out.write("            \t});\r\n");
      out.write("            \t\r\n");
      out.write("            \t\r\n");
      out.write("            \t\r\n");
      out.write("                $('.personReview').css('display','none');\r\n");
      out.write("                \r\n");
      out.write("                $('.personInfo').click(function(){\r\n");
      out.write("                \t$(this).next().slideToggle();\r\n");
      out.write("                \tvar score = $(this).next().children('div').eq(0).text()-1;\r\n");
      out.write("                \t$(this).next().children('label').eq(1).children('a').eq(score).addClass(\"on\").prevAll('a').addClass('on');\r\n");
      out.write("                })\r\n");
      out.write("                \r\n");
      out.write("                $('#reviewWriteText').css('display','none');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
 if ( rScore.getScore() < 1.5 ) {
      out.write("\r\n");
      out.write("                \t$(\"#star_grade a\").eq(0).addClass(\"on\").prevAll(\"a\").addClass(\"on\").preventEvent();\r\n");
      out.write("\t\t\t\t");
 } else if ( rScore.getScore() < 2.5 ) {
      out.write("\r\n");
      out.write("            \t\t$(\"#star_grade a\").eq(1).addClass(\"on\").prevAll(\"a\").addClass(\"on\").preventEvent();\r\n");
      out.write("\t\t\t\t");
 } else if ( rScore.getScore() < 3.5 ) {
      out.write("\r\n");
      out.write("        \t\t\t$(\"#star_grade a\").eq(2).addClass(\"on\").prevAll(\"a\").addClass(\"on\").preventEvent();\r\n");
      out.write("\t\t\t\t");
 } else if ( rScore.getScore() < 4.5 ) {
      out.write("\r\n");
      out.write("            \t\t$(\"#star_grade a\").eq(3).addClass(\"on\").prevAll(\"a\").addClass(\"on\").preventEvent();\r\n");
      out.write("\t\t\t\t");
 } else {
      out.write("\r\n");
      out.write("\t\t\t\t\t$(\"#star_grade a\").eq(4).addClass(\"on\").prevAll(\"a\").addClass(\"on\").preventEvent();\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("        ");
 if(m != null) {
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\t      $(function(){\r\n");
      out.write("\t    \t  $('#wReviewbtn').click(function(){\r\n");
      out.write("                 \t$('#reviewWriteText').slideToggle();\r\n");
      out.write("              });\r\n");
      out.write("\t    \t  \r\n");
      out.write("\t    \t  $('#rwbtn2').click(function(){\r\n");
      out.write("\t    \t\t  \r\n");
      out.write("          \t\tif($('#star_grade_review a.on').length>=1){\r\n");
      out.write("          \t\t\t\r\n");
      out.write("          \t\t\t$.ajax({\r\n");
      out.write("   \t    \t\t\t url:\"/siktam/rInsertCheck.ro\",\r\n");
      out.write("   \t    \t\t\t type:\"get\",\r\n");
      out.write("   \t    \t\t\t data: {\r\n");
      out.write("   \t    \t\t\t\t userId : \"");
      out.print(m.getUserId());
      out.write("\",\r\n");
      out.write("   \t    \t\t\t\t shopPid : \"");
      out.print(s.getShopPid());
      out.write("\"\r\n");
      out.write("   \t    \t\t\t }, success:function(data){\r\n");
      out.write("   \t    \t\t\t\t \r\n");
      out.write("   \t    \t\t\t\t if(data>=1){\r\n");
      out.write("   \t    \t\t\t\t\t alert('작성 가능 합니다.');\r\n");
      out.write("   \t    \t\t\t\t\t $('#rwbtn1').css(\"display\",\"block\");\r\n");
      out.write("   \t    \t\t\t\t\t $('#rwbtn2').css(\"display\",\"none\");\r\n");
      out.write("   \t    \t\t\t\t\t\r\n");
      out.write("   \t    \t\t\t\t }else{\r\n");
      out.write("   \t    \t\t\t\t\t alert(\"작성 할 수 있는 리뷰가 없습니다.\");\r\n");
      out.write("   \t    \t\t\t\t }\r\n");
      out.write("   \t    \t\t\t\t \r\n");
      out.write("   \t    \t\t\t }, error:function(){\r\n");
      out.write("   \t    \t\t\t\t console.log(\"ajax실패\");\r\n");
      out.write("   \t    \t\t\t }\r\n");
      out.write("   \t    \t\t  });\r\n");
      out.write("\t\t    \r\n");
      out.write("          \t\t}else {\r\n");
      out.write("          \t\t\talert(\"별점을 입력해 주세요.\");\r\n");
      out.write("          \t\t}\r\n");
      out.write("          \t\r\n");
      out.write("          \t});\r\n");
      out.write("\t    \t  \r\n");
      out.write("\t    \t  $('#rwbtn1').click(function(){\r\n");
      out.write("\t    \t\t  \r\n");
      out.write("\t    \t  \t$('#reviewForm').attr(\"action\",\"/siktam/rInsert.ro?shopPid=");
      out.print(s.getShopPid());
      out.write("&userId=");
      out.print(m.getUserId());
      out.write("&rScore=\"\r\n");
      out.write("          \t\t\t+$('#star_grade_review a.on').length);\r\n");
      out.write("\t    \t  });\r\n");
      out.write("\t    \t  \r\n");
      out.write("\t    \t  $('.deleteBtn').click(function(){\r\n");
      out.write("\t    \t\t  var check = $(this).prev('label').text();\r\n");
      out.write("\t    \t\t  console.log(check);\r\n");
      out.write("\t    \t\t  if(confirm(\"정말 삭제 하시겠습니까?\")){\r\n");
      out.write("\t    \t\t \tlocation.href=\"/siktam/rDelete.ro?reviewNo=\"+check+\"&shopPid=");
      out.print(s.getShopPid());
      out.write("\"+\"&userId=");
      out.print(m.getUserId());
      out.write("\";\r\n");
      out.write("\t    \t\t  }\r\n");
      out.write("\t    \t  });\r\n");
      out.write("\t    \t  \r\n");
      out.write("\t      });\r\n");
      out.write("        ");
 }else{
      out.write("\r\n");
      out.write("        \t$(function(){\r\n");
      out.write("\t    \t  $('#wReviewbtn').click(function(){\r\n");
      out.write("               \talert(\"로그인 먼저 해주세요!\");\r\n");
      out.write("            });\r\n");
      out.write("\t      });\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("           \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 푸터 시작 -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<footer>\r\n");
      out.write("    <div id=\"footerArea\">\r\n");
      out.write("    <p>\r\n");
      out.write("\t\t<b>식탐</b><br>\r\n");
      out.write("\t\t서울시 강남구 역상동 테헤란로 12길 남도빌딩 kh정보교육원 3층 h클래스 <br>\r\n");
      out.write("\t\t대표자 : 상또두리 | 사업자 등록번호 : 328478-24-2348971<br>\r\n");
      out.write("\t\t전화 : 010365656 | 팩스 : 0236541255| honbabsiktam.co.kr<br>\r\n");
      out.write("        <b>Copyright ⓒ 식탐 All rights reserved</b>\r\n");
      out.write("    </p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
