/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-25 15:55:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.kh.semi.reservation.model.vo.*;
import java.util.*;
import java.util.ArrayList;
import com.kh.semi.shop.model.vo.Shop;
import com.kh.semi.member.model.vo.*;

public final class reservation_005f4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1582645757249L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1582645755766L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.kh.semi.member.model.vo");
    _jspx_imports_packages.add("com.kh.semi.reservation.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.semi.shop.model.vo.Shop");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<ReservationTest> list = (ArrayList<ReservationTest>) request.getAttribute("list");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>예약페이지</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/siktam/resources/css/headerfooterLayout.css\">\r\n");
      out.write("<!-- 추가 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Montserrat\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- x버튼 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/siktam/resources/css/reservation_4.css\">\r\n");
      out.write("<!-- datepicker -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<!-- timepicker -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 헤더 시작 -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member m = (Member)session.getAttribute("member");
	ArrayList<Shop> slist=new ArrayList<Shop>();
	if(m!=null&&m.getShopYN().equals("Y")){
		slist=(ArrayList<Shop>)session.getAttribute("shop");		
	}else{
		slist=null;
	}
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <nav id=\"nav\">\n");
      out.write("    \t<div id=\"logodiv\"><a href=\"/siktam/listMain.ma\"><img id=\"logo\" src=\"/siktam/resources/images/KakaoTalk_20200101_193858750.png\" alt=\"\" style=\"width:50px; height:50px; margin-top:10px;\"></a></div>\r\n");
      out.write("\r\n");
      out.write("    \t<div id=\"navp\">\r\n");
      out.write("\t        ");
 if(m!=null && m.getUserId().equals("4dich")){ 
      out.write("\r\n");
      out.write("\t        \t<a class=\"navp\" href=\"/siktam/views/admin_main_4.jsp\"><span>관리자</span></a>\r\n");
      out.write("\t        ");
 } 
      out.write("\r\n");
      out.write("            <a class=\"navp\" href=\"/siktam/nselectList.no\"><span>공지사항</span></a>\r\n");
      out.write("            <a class=\"navp\" href=\"/siktam/QnaListServlet\"><span>문의사항</span></a>\r\n");
      out.write("            ");
if(m==null) {
      out.write("\r\n");
      out.write("            ");
}else if(m.getShopYN().equals("N")){
      out.write("\r\n");
      out.write("            \t<a class=\"navp\" href=\"/siktam/mypageMember.mm\"><span>마이페이지</span></a>\r\n");
      out.write("            ");
}else{ 
      out.write("\r\n");
      out.write("            \t<a class=\"navp\" href=\"/siktam/views/mypageShop_5.jsp\"><span>마이페이지</span></a>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            ");
 if(m==null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<a class=\"navp\" href=\"/siktam/views/login_2.jsp\"><span style=\"border: 2px solid rgb(13, 78, 100); color:rgb(13, 78, 100); background-color:white; padding:5px\">로그인</span></a>\r\n");
      out.write("            ");
 }else{ 
      out.write("\r\n");
      out.write("            \t<a class=\"navp\" onclick=\"location.href='/siktam/logout.do'; alert('로그아웃되었습니다')\"><span style=\"cursor: pointer; border: 2px solid rgb(13, 78, 100); color:rgb(13, 78, 100); background-color:white; padding:5px\">로그아웃</span></a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 이 안에 작업하기 -->\r\n");
      out.write("\t<form method=\"POST\" target=\"_self\" action=\"pay.pc\">\r\n");
      out.write("\t\t<div id=\"title\">\r\n");
      out.write("\t\t\t<div id=\"titleImg\">\r\n");
      out.write("\t\t\t\t<img src=\"/siktam/resources/images/udon.png\" alt=\"\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"titleText\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t<b>");
      out.print(list.get(0).getShopName());
      out.write("</b>(예약하기)\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<p>");
      out.print(list.get(0).getShopAddr());
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"shopPid\" value=\"");
      out.print( list.get(0).getShopPid() );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"shopName\" value=\"");
      out.print(list.get(0).getShopName());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"shopAddr\" value=\"");
      out.print(list.get(0).getShopAddr());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"date-time\">\r\n");
      out.write("\t\t\t<div id=\"date\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-calendar\"></span> 예약 일자\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"datepicker\" name=\"date\">\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"time\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-time\"></span> 예약 시간\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id='timepicker' name=\"time\">\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"menu-result\">\r\n");
      out.write("\t\t\t<div id=\"menu1\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-list-alt\"></span> 메뉴\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<div id=\"menuType\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"tab-1\" class=\"tab-content current\">\r\n");
      out.write("\t\t\t\t\t<table id=\"tbl\">\r\n");
      out.write("\t\t\t\t\t\t");
for (ReservationTest r : list) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><img src=\"/siktam/resources/images/03.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 100px\" alt=\"Image\" class=\"img-thumbnail\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(r.getMenuName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(r.getMenuPrice());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>0</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"display:none\">");
      out.print(r.getMenuNo());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><img src=\"/siktam/resources/images/leftArrow.png\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\twidth=\"10\" height=\"10\" class=\"bt_down\" /><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"/siktam/resources/images/rightArrow.png\" alt=\"\" width=\"10\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"10\" class=\"bt_up\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"result1\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-check\"></span> 주문표\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<div id=\"result2\">\r\n");
      out.write("\t\t\t\t\t<div id=\"result3\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"resultTable\">\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"result5\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"tblSum\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>결제 금액</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"result4\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"결제\" id=\"btnSubmit\" class=\"btn\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"reset\" value=\"취소\" id=\"btnReset\" class=\"btn\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"location.href = 'productDetailPage_6.jsp';\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$('.bt_up').click(function() {\r\n");
      out.write("\t\t\t\tvar n = $('.bt_up').index(this);\r\n");
      out.write("\t\t\t\tvar num = $('#tbl tr:eq('+ n +')').children().eq(3).text();\r\n");
      out.write("\t\t\t\tnum = $('#tbl tr:eq('+ n +')').children().eq(3).text(num * 1 + 1);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar m0 = []\r\n");
      out.write("\t\t\t\tfor(var i=0; i<$('#tbl tr').length; i++){\r\n");
      out.write("\t\t\t\t\tm0.push($('#tbl tr:eq('+i+')').children().eq(1).text());\r\n");
      out.write("\t\t\t\t    m0.push($('#tbl tr:eq('+i+')').children().eq(2).text());\r\n");
      out.write("\t\t\t\t\tm0.push($('#tbl tr:eq('+i+')').children().eq(3).text());\r\n");
      out.write("\t\t\t\t\tm0.push($('#tbl tr:eq('+i+')').children().eq(4).text());\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t url:\"/siktam/reservationPay.rc\",\r\n");
      out.write("\t\t\t         type:\"get\",\r\n");
      out.write("\t\t\t         traditional : true,\r\n");
      out.write("\t\t\t         dataType:\"json\",\r\n");
      out.write("\t\t\t         data:{\r\n");
      out.write("\t\t\t               \"m0list\" : m0\r\n");
      out.write("\t\t\t         },success:function(data){\r\n");
      out.write("\t\t\t           console.log(data);\r\n");
      out.write("\t\t\t         \r\n");
      out.write("\t\t\t        $('#resultTable').find('tr').remove(); \r\n");
      out.write("\t\t\t        $('#tblSum').find('td:eq(1)').remove();\r\n");
      out.write("\t\t\t       \r\n");
      out.write("\t\t\t        $('#hdtotal').remove();\r\n");
      out.write("\t\t\t        $('#menuName').remove();\r\n");
      out.write("\t\t\t        $('#menuCount').remove();\r\n");
      out.write("\t\t\t        $('#menuPrice').remove();\r\n");
      out.write("\t\t\t        $('#menuNo').remove();\r\n");
      out.write("\t\t\t          \r\n");
      out.write("\t\t\t        for(var i=0; i<data.length; i++){\r\n");
      out.write("\t\t\t        \tvar $tr = $('<tr>');\r\n");
      out.write("\t\t\t        \tvar $menuName = $('<td>').text(data[i].menuName);\r\n");
      out.write("\t\t\t        \tvar $menuCount = $('<td>').text(data[i].menuCount);\r\n");
      out.write("\t\t\t        \tvar $menuPrice = $('<td>').text(data[i].menuPrice);\r\n");
      out.write("\t\t\t        \tvar $hdN = $('<input type=\"hidden\" id=\"menuName\" name=\"menuName\" value=\"'+data[i].menuName+'\">');\r\n");
      out.write("\t\t\t        \tvar $hdC = $('<input type=\"hidden\" id=\"menuCount\" name=\"menuCount\" value=\"'+data[i].menuCount+'\">');\r\n");
      out.write("\t\t\t        \tvar $hdP = $('<input type=\"hidden\" id=\"menuPrice\" name=\"menuPrice\" value=\"'+data[i].menuPrice+'\">');\r\n");
      out.write("\t\t\t        \tvar $hdMN = $('<input type=\"hidden\" id=\"menuNo\" name=\"menuNo\" value=\"'+data[i].menuNo+'\">');\r\n");
      out.write("\t\t\t        \t\r\n");
      out.write("\t\t\t        \t$tr.append($menuName);\r\n");
      out.write("\t\t\t        \t$tr.append($hdN)\r\n");
      out.write("\t\t\t        \t$tr.append($menuCount);\r\n");
      out.write("\t\t\t        \t$tr.append($hdC)\r\n");
      out.write("\t\t\t        \t$tr.append($menuPrice);\r\n");
      out.write("\t\t\t        \t$tr.append($hdP)\r\n");
      out.write("\t\t\t        \t$tr.append($hdMN);   \r\n");
      out.write("\t\t\t        \t\r\n");
      out.write("\t\t\t        \t$('#resultTable').append($tr);\r\n");
      out.write("\t\t\t        \t   \r\n");
      out.write("\t\t\t        \t$td = $('<td>'); \r\n");
      out.write("\t\t\t        \t$total = $('<td>').text(data[data.length-1].total);\r\n");
      out.write("\t\t\t        \t$hdTag = $('<input type=\"hidden\" id=\"hdtotal\" name=\"hdtotal\" value=\"'+data[data.length-1].total+'\">');\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        \t$('#tblSum').append($total).append($hdTag);\r\n");
      out.write("\t\t\t        \t  \r\n");
      out.write("\t\t\t           \r\n");
      out.write("\t\t\t         },error:function(){\r\n");
      out.write("\t\t\t         }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('.bt_down').click(function() {\r\n");
      out.write("\t\t\t\tvar n = $('.bt_down').index(this);\r\n");
      out.write("\t\t\t\tvar num = $('#tbl tr:eq('+ n +')').children().eq(3).text();\r\n");
      out.write("\t\t\t\tif (parseInt(num) > 0) {\r\n");
      out.write("\t\t\t\t\tnum = $('#tbl tr:eq('+ n +')').children().eq(3).text(num * 1 - 1);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\tvar m0 = []\r\n");
      out.write("\t\t\t\tfor(var i=0; i<$('#tbl tr').length; i++){\r\n");
      out.write("\t\t\t\t\tm0.push($('#tbl tr:eq('+i+')').children().eq(1).text());\r\n");
      out.write("\t\t\t\t\tm0.push($('#tbl tr:eq('+i+')').children().eq(2).text());\r\n");
      out.write("\t\t\t\t\tm0.push($('#tbl tr:eq('+i+')').children().eq(3).text());\r\n");
      out.write("\t\t\t\t\tm0.push($('#tbl tr:eq('+i+')').children().eq(4).text());\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t url:\"/siktam/reservationPay.rc\",\r\n");
      out.write("\t\t\t         type:\"get\",\r\n");
      out.write("\t\t\t         traditional : true,\r\n");
      out.write("\t\t\t         dataType:\"json\",\r\n");
      out.write("\t\t\t         data:{\r\n");
      out.write("\t\t\t        \t \"m0list\" : m0\r\n");
      out.write("\t\t\t         }\r\n");
      out.write("\t\t\t         ,success:function(data){\r\n");
      out.write("\t\t\t           console.log(data);\r\n");
      out.write("\t\t\t            $('#resultTable').find('tr').remove(); \r\n");
      out.write("\t\t\t\t        $('#tblSum').find('td:eq(1)').remove();\r\n");
      out.write("\t\t\t\t        $('#hdtotal').remove();\r\n");
      out.write("\t\t\t\t        $('#menuName').remove();\r\n");
      out.write("\t\t\t\t        $('#menuCount').remove();\r\n");
      out.write("\t\t\t\t        $('#menuPrice').remove();\r\n");
      out.write("\t\t\t\t        $('#menuNo').remove();\r\n");
      out.write("\t\t\t\t          \r\n");
      out.write("\t\t\t\t        for(var i=0; i<data.length; i++){\r\n");
      out.write("\t\t\t\t        \tvar $tr = $('<tr>');\r\n");
      out.write("\t\t\t\t        \tvar $menuName = $('<td>').text(data[i].menuName);\r\n");
      out.write("\t\t\t\t        \tvar $menuCount = $('<td>').text(data[i].menuCount);\r\n");
      out.write("\t\t\t\t        \tvar $menuPrice = $('<td>').text(data[i].menuPrice);\r\n");
      out.write("\t\t\t\t        \tvar $hdN = $('<input type=\"hidden\" id=\"menuName\" name=\"menuName\" value=\"'+data[i].menuName+'\">');\r\n");
      out.write("\t\t\t\t        \tvar $hdC = $('<input type=\"hidden\" id=\"menuCount\" name=\"menuCount\" value=\"'+data[i].menuCount+'\">');\r\n");
      out.write("\t\t\t\t        \tvar $hdP = $('<input type=\"hidden\" id=\"menuPrice\" name=\"menuPrice\" value=\"'+data[i].menuPrice+'\">');\r\n");
      out.write("\t\t\t\t        \tvar $hdMN = $('<input type=\"hidden\" id=\"menuNo\" name=\"menuNo\" value=\"'+data[i].menuNo+'\">');\r\n");
      out.write("\t\t\t\t        \t   \r\n");
      out.write("\t\t\t\t        \t$tr.append($menuName);\r\n");
      out.write("\t\t\t\t        \t$tr.append($hdN);\r\n");
      out.write("\t\t\t\t        \t$tr.append($menuCount);\r\n");
      out.write("\t\t\t\t        \t$tr.append($hdC);\r\n");
      out.write("\t\t\t\t        \t$tr.append($menuPrice);\r\n");
      out.write("\t\t\t\t        \t$tr.append($hdP);\r\n");
      out.write("\t\t\t\t        \t$tr.append($hdMN);\r\n");
      out.write("\t\t\t\t        \t   \r\n");
      out.write("\t\t\t\t        \t$('#resultTable').append($tr);\r\n");
      out.write("\t\t\t\t        \t   \r\n");
      out.write("\t\t\t\t        \t$td = $('<td>'); \r\n");
      out.write("\t\t\t\t        \t$total = $('<td>').text(data[data.length-1].total);\r\n");
      out.write("\t\t\t\t        \t$hdTag = $('<input type=\"hidden\" id=\"hdtotal\" name=\"hdtotal\" value=\"'+data[data.length-1].total+'\">');\r\n");
      out.write("\t\t\t\t        }\r\n");
      out.write("\t\t\t\t        \t$('#tblSum').append($total).append($hdTag);\r\n");
      out.write(" \t\t\t         },error:function(){\r\n");
      out.write(" \t\t\t        \t console.log(\"에러\");\r\n");
      out.write("\t\t\t         }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$('#timepicker').timepicker({\r\n");
      out.write("\t\t\t\ttimeFormat : 'HH:mm',\r\n");
      out.write("\t\t\t\tinterval : 30,\r\n");
      out.write("\t\t\t\tminTime :'");
      out.print(list.get(0).getShopStartTime());
      out.write("',\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\tmaxTime :'23:59',\r\n");
      out.write("\t\t\t\tdefaultTime : '");
      out.print(list.get(0).getShopStartTime());
      out.write("',\r\n");
      out.write("\t\t\t\tstartTime : '");
      out.print(list.get(0).getShopStartTime());
      out.write("',\r\n");
      out.write("\t\t\t\tdynamic : false,\r\n");
      out.write("\t\t\t\tdropdown : true,\r\n");
      out.write("\t\t\t\tscrollbar : true\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t//input을 datepicker로 선언\r\n");
      out.write("\t\t$(\"#datepicker\").datepicker(\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdateFormat : 'yy-mm-dd' //Input Display Format 변경\r\n");
      out.write("\t\t\t\t,showOtherMonths : true //빈 공간에 현재월의 앞뒤월의 날짜를 표시\r\n");
      out.write("\t\t\t\t,showMonthAfterYear : true //년도 먼저 나오고, 뒤에 월 표시\r\n");
      out.write("\t\t\t\t,changeYear : true //콤보박스에서 년 선택 가능\r\n");
      out.write("\t\t\t\t,changeMonth : true //콤보박스에서 월 선택 가능                \r\n");
      out.write("\t\t\t\t,showOn : \"both\" //button:버튼을 표시하고,버튼을 눌러야만 달력 표시 ^ both:버튼을 표시하고,버튼을 누르거나 input을 클릭하면 달력 표시  \r\n");
      out.write("\t\t\t\t,buttonImage : \"http://jqueryui.com/resources/demos/datepicker/images/calendar.gif\" //버튼 이미지 경로\r\n");
      out.write("\t\t\t\t,buttonImageOnly : true //기본 버튼의 회색 부분을 없애고, 이미지만 보이게 함\r\n");
      out.write("\t\t\t\t,buttonText : \"선택\" //버튼에 마우스 갖다 댔을 때 표시되는 텍스트                \r\n");
      out.write("\t\t\t\t,yearSuffix : \"년\" //달력의 년도 부분 뒤에 붙는 텍스트\r\n");
      out.write("\t\t\t\t,monthNamesShort : [ '1', '2', '3', '4', '5', '6',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t'7', '8', '9', '10', '11', '12' ] //달력의 월 부분 텍스트\r\n");
      out.write("\t\t\t\t,monthNames : [ '1월', '2월', '3월', '4월', '5월', '6월',\r\n");
      out.write("\t\t\t\t\t\t\t  '7월', '8월', '9월', '10월', '11월', '12월' ] //달력의 월 부분 Tooltip 텍스트\r\n");
      out.write("\t\t\t\t,dayNamesMin : [ '일', '월', '화', '수', '목', '금', '토' ] //달력의 요일 부분 텍스트\r\n");
      out.write("\t\t\t\t,dayNames : [ '일요일', '월요일', '화요일', '수요일', '목요일','금요일', '토요일' ] //달력의 요일 부분 Tooltip 텍스트\r\n");
      out.write("\t\t\t\t,minDate : \"0\" //최소 선택일자(-1D:하루전, -1M:한달전, -1Y:일년전)\r\n");
      out.write("\t\t\t\t,maxDate : \"+1M\" //최대 선택일자(+1D:하루후, -1M:한달후, -1Y:일년후)\r\n");
      out.write("\t\t\t\t,beforeShowDay : function(date) {\r\n");
      out.write("\t\t\t\t\tvar day = date.getDay();\r\n");
      out.write("\t\t\t\t\t");
int shopDay=0;
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 if(list.get(0).getShopDay().equals("일")){
					shopDay = 0;
					}
					if(list.get(0).getShopDay().equals("월")){
					shopDay = 1;
					}
					if(list.get(0).getShopDay().equals("화")){
					shopDay = 2;
					}
					if(list.get(0).getShopDay().equals("수")){
					shopDay = 3;
					}
					if(list.get(0).getShopDay().equals("목")){
					shopDay = 4;
					}
					if(list.get(0).getShopDay().equals("금")){
					shopDay = 5;
					}
					if(list.get(0).getShopDay().equals("토")){
					shopDay = 6;
					}
					if(list.get(0).getShopDay().equals("연중무휴")){
					shopDay = 7;
					}
      out.write("\r\n");
      out.write("\t\t\t\t\treturn [ (day != '");
      out.print(shopDay);
      out.write("'\r\n");
      out.write("\t\t\t\t\t)];\r\n");
      out.write("\t\t\t\t }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//초기값을 오늘 날짜로 설정\r\n");
      out.write("\t\t$('#datepicker').datepicker('setDate', 'today'); //(-1D:하루전, -1M:한달전, -1Y:일년전), (+1D:하루후, -1M:한달후, -1Y:일년후)        \r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 푸터 시작 -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<footer>\r\n");
      out.write("    <div id=\"footerArea\">\r\n");
      out.write("    <p>\r\n");
      out.write("\t\t<b>식탐</b><br>\r\n");
      out.write("\t\t서울시 강남구 역상동 테헤란로 12길 남도빌딩 kh정보교육원 3층 h클래스 <br>\r\n");
      out.write("\t\t대표자 : 상또두리 | 사업자 등록번호 : 328478-24-2348971<br>\r\n");
      out.write("\t\t전화 : 010365656 | 팩스 : 0236541255| honbabsiktam.co.kr<br>\r\n");
      out.write("        <b>Copyright ⓒ 식탐 All rights reserved</b>\r\n");
      out.write("    </p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
